name: Build OpenTelemetry Demo App Environment on AWS and Deploy to EKS Cluster

on:
  push:
    branches:
      - 'deploy/**'
      - 'feat/k8s'
      - main

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
  CI_RUNNER_ROLE: ${{ secrets.CI_RUNNER_ROLE }}


jobs:
  # check-prerequisites:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "Check/Install Prerequisites"
  #       run: |
  #         echo "Checking all the runtime prerequisites" 
  #         aws --version
  #       continue-on-error: false

  build_aws:
    runs-on: ubuntu-latest
    # needs: check-prerequisites
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set up AWS CLI"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.11.2

      # - name: "Check Prerequisite Commands"
      #   run: |
      #     aws sts get-caller-identity
      #     terraform --version
      #   continue-on-error: false

      - name: "Initialize Terraform and Create Deployment Plan"
        run: |
          terraform init
          terraform validate
          terraform plan -out=otel.plan 

      - name: "Apply Terraform Plan"
        run: |
          terraform apply -auto-approve otel.plan
        continue-on-error: false

      - name: "Save Terraform Outputs"
        id: tf_outputs
        run: |
          MGMT_IP=$(terraform output -raw k8s_management_instance_public_ip)
          echo "k8s_mgmt_ip=$MGMT_IP" >> $GITHUB_OUTPUT

      - name: "Test Variables"
        run: |
          echo "k8s_ec2_instance_ip is ${{ steps.tf_outputs.outputs.k8s_mgmt_ip }}"
