name: Build OpenTelemetry Demo App Environment on AWS and Deploy to EKS Cluster

on:
  push:
    branches:
      - 'deploy/**'
      - main

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
  CI_RUNNER_ROLE: ${{ secrets.CI_RUNNER_ROLE }}


jobs:
  check-prerequisites:
    runs-on: ubuntu-latest
    steps:
      - name: "Check/Install Prerequisites"
        run: |
          echo "Checking all the runtime prerequisites" 
          aws --version
          terraform --version
        continue-on-error: false

  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set up AWS CLI"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.11.2

      - name: "Test Commands"
        run: |
          aws --version
          terraform --version
          
